x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:  
  # L1BR and Laser Simulation on Gazebo (and Rviz) Nodes
  laser_l1br:
    container_name: laser_l1br
    build: .
    <<: [ *net-config, *gpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch ugv_simulation l1br_laserworld.launch.py use_sim_time:=true

  slam:
    image: husarion/navigation2:humble-1.1.6-20230427-stable
    <<: *net-config
    volumes:
      - ./config/slam_params.yaml:/params.yaml
      - ./maps:/maps
    command: >
      ros2 launch nav2_bringup slam_launch.py
        params_file:=/params.yaml
        use_sim_time:=True
        map:=/maps/map.yaml
  
  navigation:
    image: husarion/navigation2:humble-1.1.6-20230427-stable
    <<: *net-config
    depends_on:
      slam: { condition: service_healthy }
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
    command: >
      bash -c "
      ros2 launch nav2_bringup navigation_launch.py 
      params_file:=/nav2_params.yaml 
      use_sim_time:=True; 
      "

  explore:
    container_name: explore
    build: .
    <<: [ *net-config, *gpu-config ]
    depends_on:
      slam: { condition: service_healthy }
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch explore_lite explore.launch.py